include ~/.config/theme/kitty/current

font_family JetBrainsMono Nerd Font
font_size 10.0
background_opacity 0.8
confirm_os_window_close 0

cursor_trail 1

map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

# splits
map alt+| launch --location=vsplit --cwd=current
map alt+- launch --location=hsplit --cwd=current

map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

map alt+shift+h move_window left
map alt+shift+l move_window right
map alt+shift+k move_window up
map alt+shift+j move_window down

# commands
map alt+y launch --type=background --stdin-source=@last_cmd_output wl-copy
map alt+s show_scrollback
