# plugins
eval "$(sheldon source)"

source ~/.config/zsh/alias
[ -f ~/.env.sh ] && source ~/.env.sh

# colors
test -r ~/.config/theme/dircolors/current && eval "$(dircolors ~/.config/theme/dircolors/current)"
export BAT_THEME=Nord

# fzf
source ~/.config/zsh/fzf.zsh
eval "$(fzf --zsh)"

# prompt
[ $TERM != "linux" ] && export STARSHIP_CONFIG=~/.config/starship/starship.toml && eval "$(starship init zsh)"
